<?php
function getToolBrandingPresets(): array {
    return [
        'excel' => ['start' => '#2E7D32', 'end' => '#1B5E20', 'start_opacity' => 90, 'end_opacity' => 90],
        'power-bi' => ['start' => '#FFC400', 'end' => '#CC7800', 'start_opacity' => 92, 'end_opacity' => 90],
        'sql' => ['start' => '#3F51B5', 'end' => '#21358C', 'start_opacity' => 90, 'end_opacity' => 90],
        'statistics' => ['start' => '#009688', 'end' => '#00695C', 'start_opacity' => 90, 'end_opacity' => 90],
        'tableau' => ['start' => '#E97627', 'end' => '#00567A', 'start_opacity' => 92, 'end_opacity' => 90],
        'looker-studio' => ['start' => '#1A73E8', 'end' => '#0D47A1', 'start_opacity' => 92, 'end_opacity' => 90],
        'ibm-cognos' => ['start' => '#0F62FE', 'end' => '#0043CE', 'start_opacity' => 92, 'end_opacity' => 90],
        'default' => ['start' => '#A8324E', 'end' => '#6C1E35', 'start_opacity' => 90, 'end_opacity' => 90],
    ];
}

function getToolSeedData(): array {
    $branding = getToolBrandingPresets();

    $topics = [
        'excel' => [
            'slug' => 'excel',
            'title_en' => 'Microsoft Excel',
            'title_ar' => 'مايكروسوفت إكسل',
            'intro_en' => 'Master data analysis and visualization with Microsoft Excel. Learn formulas, pivot tables, charts, and advanced data manipulation techniques.',
            'intro_ar' => 'أتقن تحليل البيانات والتصور باستخدام مايكروسوفت إكسل. تعلم الصيغ والجداول المحورية والمخططات وتقنيات معالجة البيانات المتقدمة.',
            'hero_image' => 'https://via.placeholder.com/1200x400/4CAF50/ffffff?text=Excel',
            'hero_overlay_color_start' => $branding['excel']['start'],
            'hero_overlay_color_end' => $branding['excel']['end'],
            'hero_overlay_opacity_start' => $branding['excel']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['excel']['end_opacity'],
            'display_order' => 1,
            'is_tool' => true,
        ],
        'power-bi' => [
            'slug' => 'power-bi',
            'title_en' => 'Power BI',
            'title_ar' => 'باور بي آي',
            'intro_en' => 'Create interactive dashboards and powerful visualizations with Microsoft Power BI. Transform raw data into actionable insights.',
            'intro_ar' => 'قم بإنشاء لوحات معلومات تفاعلية وتصورات قوية باستخدام مايكروسوفت باور بي آي. حول البيانات الأولية إلى رؤى قابلة للتنفيذ.',
            'hero_image' => 'https://via.placeholder.com/1200x400/FF9800/ffffff?text=Power+BI',
            'hero_overlay_color_start' => $branding['power-bi']['start'],
            'hero_overlay_color_end' => $branding['power-bi']['end'],
            'hero_overlay_opacity_start' => $branding['power-bi']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['power-bi']['end_opacity'],
            'display_order' => 2,
            'is_tool' => true,
        ],
        'statistics' => [
            'slug' => 'statistics',
            'title_en' => 'Statistics',
            'title_ar' => 'الإحصاء',
            'intro_en' => 'Understand statistical concepts, probability distributions, hypothesis testing, and data modeling techniques used by analysts every day.',
            'intro_ar' => 'افهم المفاهيم الإحصائية وتوزيعات الاحتمالات واختبار الفرضيات وتقنيات نمذجة البيانات التي يستخدمها المحللون يوميًا.',
            'hero_image' => 'https://via.placeholder.com/1200x400/009688/ffffff?text=Statistics',
            'hero_overlay_color_start' => $branding['statistics']['start'],
            'hero_overlay_color_end' => $branding['statistics']['end'],
            'hero_overlay_opacity_start' => $branding['statistics']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['statistics']['end_opacity'],
            'display_order' => 3,
            'is_tool' => true,
        ],
        'sql' => [
            'slug' => 'sql',
            'title_en' => 'SQL & Databases',
            'title_ar' => 'قواعد البيانات و SQL',
            'intro_en' => 'Write efficient SQL queries, model relational data, and power analytics dashboards with optimized views and materialized tables.',
            'intro_ar' => 'اكتب استعلامات SQL فعّالة، ونمذج البيانات العلائقية، وشغّل لوحات التحليلات باستخدام العروض المحسّنة والجداول المادية.',
            'hero_image' => 'https://via.placeholder.com/1200x400/3F51B5/ffffff?text=SQL',
            'hero_overlay_color_start' => $branding['sql']['start'],
            'hero_overlay_color_end' => $branding['sql']['end'],
            'hero_overlay_opacity_start' => $branding['sql']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['sql']['end_opacity'],
            'display_order' => 4,
            'is_tool' => true,
        ],
        'tableau' => [
            'slug' => 'tableau',
            'title_en' => 'Tableau',
            'title_ar' => 'تابلو',
            'intro_en' => 'Design interactive Tableau dashboards, optimize extracts, and publish governed data sources that teams can trust.',
            'intro_ar' => 'صمّم لوحات Tableau تفاعلية، وحسّن الجداول المستخلصة، وانشر مصادر بيانات منضبطة يمكن للفرق الوثوق بها.',
            'hero_image' => 'https://via.placeholder.com/1200x400/F26420/ffffff?text=Tableau',
            'hero_overlay_color_start' => $branding['tableau']['start'],
            'hero_overlay_color_end' => $branding['tableau']['end'],
            'hero_overlay_opacity_start' => $branding['tableau']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['tableau']['end_opacity'],
            'display_order' => 5,
            'is_tool' => true,
        ],
        'looker-studio' => [
            'slug' => 'looker-studio',
            'title_en' => 'Looker Studio',
            'title_ar' => 'لوكر ستوديو',
            'intro_en' => 'Build marketing and product performance reports in Looker Studio with BigQuery, GA4, and Sheets sources.',
            'intro_ar' => 'ابنِ تقارير أداء التسويق والمنتج في Looker Studio باستخدام مصادر BigQuery و GA4 و Sheets.',
            'hero_image' => 'https://via.placeholder.com/1200x400/1A73E8/ffffff?text=Looker+Studio',
            'hero_overlay_color_start' => $branding['looker-studio']['start'],
            'hero_overlay_color_end' => $branding['looker-studio']['end'],
            'hero_overlay_opacity_start' => $branding['looker-studio']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['looker-studio']['end_opacity'],
            'display_order' => 6,
            'is_tool' => true,
        ],
        'ibm-cognos' => [
            'slug' => 'ibm-cognos',
            'title_en' => 'IBM Cognos',
            'title_ar' => 'آي بي إم كوجنوس',
            'intro_en' => 'Deliver enterprise-grade reporting, AI-assisted insights, and automated distribution workflows in IBM Cognos.',
            'intro_ar' => 'قدّم تقارير بمستوى المؤسسات ورؤى مدعومة بالذكاء الاصطناعي وتدفقات توزيع تلقائية في IBM Cognos.',
            'hero_image' => 'https://via.placeholder.com/1200x400/0F62FE/ffffff?text=IBM+Cognos',
            'hero_overlay_color_start' => $branding['ibm-cognos']['start'],
            'hero_overlay_color_end' => $branding['ibm-cognos']['end'],
            'hero_overlay_opacity_start' => $branding['ibm-cognos']['start_opacity'],
            'hero_overlay_opacity_end' => $branding['ibm-cognos']['end_opacity'],
            'display_order' => 7,
            'is_tool' => true,
        ],
    ];

    $content = [
        'tableau' => [
            [
                'slug' => 'visual-best-practices',
                'title_en' => 'Visual Best Practices & Storytelling',
                'title_ar' => 'أفضل ممارسات التصور وسرد القصة',
                'summary_en' => 'Blend color, typography, and hierarchy guidelines with Tableau layouts that spotlight the “so what.”',
                'summary_ar' => 'ادمج إرشادات الألوان والخطوط والتدرج مع تصاميم Tableau التي تبرز الرسالة الأساسية.',
                'body_en' => '<h2>Design Frameworks</h2><p>We cover spacing systems, grid templates, and calculations that enable responsive dashboards.</p><p>Then we practice annotation, parameter actions, and navigation buttons to keep stakeholders focused.</p>',
                'body_ar' => '<h2>أطر التصميم</h2><p>نغطي أنظمة التباعد والقوالب الشبكية والحسابات التي تتيح لوحات تفاعلية.</p><p>ثم نطبق التعليقات التوضيحية وإجراءات المعاملات وأزرار التنقل للحفاظ على تركيز أصحاب المصلحة.</p>',
                'cta_note_en' => 'Craft dashboards executives remember by mastering storytelling cues.',
                'cta_note_ar' => 'اصنع لوحات يتذكرها التنفيذيون من خلال إتقان مفاتيح سرد القصة.',
                'hero_image' => 'https://via.placeholder.com/800x400/F26420/ffffff?text=Tableau+Storytelling',
                'status' => 'published',
                'display_order' => 1,
            ],
            [
                'slug' => 'server-automation',
                'title_en' => 'Server Automation & Governance',
                'title_ar' => 'الأتمتة والحَوْكمة في الخادم',
                'summary_en' => 'Deploy extracts, manage permissions, and optimize resource nodes for Tableau Server/Cloud.',
                'summary_ar' => 'قم بنشر الاستخلاصات وإدارة الصلاحيات وتحسين موارد Tableau Server/Cloud.',
                'body_en' => '<h2>Reliable Operations</h2><p>We script tabcmd flows, configure backgrounder scaling, and enforce project governance.</p><p>You also learn how to audit performance, subscriptions, and usage with Admin Views.</p>',
                'body_ar' => '<h2>تشغيل موثوق</h2><p>نبرمج عمليات tabcmd، ونضبط مقياس الخلفيات، ونطبق الحوكمة داخل المشاريع.</p><p>كما تتعلم كيف تراجع الأداء والاشتراكات والاستخدام عبر لوحات المسؤول.</p>',
                'cta_note_en' => 'Keep mission-critical dashboards healthy with proactive monitoring.',
                'cta_note_ar' => 'حافظ على صحة اللوحات الحساسة من خلال المراقبة الاستباقية.',
                'hero_image' => 'https://via.placeholder.com/800x400/00567A/ffffff?text=Tableau+Server',
                'status' => 'published',
                'display_order' => 2,
            ],
        ],
        'looker-studio' => [
            [
                'slug' => 'marketing-attribution',
                'title_en' => 'Marketing Attribution Dashboards',
                'title_ar' => 'لوحات قياس أداء التسويق',
                'summary_en' => 'Blend GA4, Ads, and Sheets data to build unified attribution scorecards.',
                'summary_ar' => 'ادمج بيانات GA4 و Ads و Sheets لبناء بطاقات متابعة موحدة.',
                'body_en' => '<h2>Unified Pipelines</h2><p>We build reusable community connectors, parameter-driven filters, and blended fields for paid/owned channels.</p><p>Templates keep refresh schedules healthy and make UTM governance simple.</p>',
                'body_ar' => '<h2>قنوات موحدة</h2><p>نبني موصلات قابلة لإعادة الاستخدام، وعوامل تصفية تعتمد على المعاملات، وحقول مدمجة لقنوات مدفوعة ومملوكة.</p><p>تضمن القوالب سلامة جداول التحديث وتبسط حوكمة UTM.</p>',
                'cta_note_en' => 'Ship agency-grade Looker Studio scorecards in record time.',
                'cta_note_ar' => 'قدّم بطاقات Looker Studio بمستوى الوكالات في وقت قياسي.',
                'hero_image' => 'https://via.placeholder.com/800x400/1A73E8/ffffff?text=Looker+Studio+Marketing',
                'status' => 'published',
                'display_order' => 1,
            ],
            [
                'slug' => 'governance-performance',
                'title_en' => 'Governance & Performance Tuning',
                'title_ar' => 'الحوكمة وتحسين الأداء',
                'summary_en' => 'Control permissions, apply row-level security, and keep reports fast for every viewer.',
                'summary_ar' => 'تحكم في الصلاحيات وطبّق أمان الصفوف واحرص على سرعة اللوحات للمستخدمين.',
                'body_en' => '<h2>Stay in Control</h2><p>We walk through Looker Studio roles, folder sharing models, and BigQuery authorized views.</p><p>Then we optimize report performance with caching, extract schedules, and lightweight visual choices.</p>',
                'body_ar' => '<h2>ابقَ مسيطرًا</h2><p>نستعرض أدوار Looker Studio ونماذج مشاركة المجلدات وطرق تفعيل عروض BigQuery المؤمنة.</p><p>بعدها نحسن أداء التقارير باستخدام التخزين المؤقت وجداول التحديث والاختيارات البصرية الخفيفة.</p>',
                'cta_note_en' => 'Scale your marketing analytics workflow with our guided sprints.',
                'cta_note_ar' => 'طوّر مسار تحليلات التسويق عندك من خلال سباقاتنا التدريبية الموجهة.',
                'hero_image' => 'https://via.placeholder.com/800x400/0D47A1/ffffff?text=Looker+Governance',
                'status' => 'published',
                'display_order' => 2,
            ],
        ],
        'ibm-cognos' => [
            [
                'slug' => 'ai-insights',
                'title_en' => 'AI-Assisted Insights & Dashboards',
                'title_ar' => 'رؤى مدعومة بالذكاء الاصطناعي ولوحات متقدمة',
                'summary_en' => 'Use Cognos AI features to surface anomalies, drivers, and narrative insights automatically.',
                'summary_ar' => 'استخدم ميزات الذكاء الاصطناعي في Cognos لاكتشاف الشذوذ ومحركات الأداء وتوليد الرؤى تلقائيًا.',
                'body_en' => '<h2>Trustworthy Augmented Analytics</h2><p>We explore the AI assistant, compare forecast quality, and highlight how to document business logic so stakeholders trust automated insights.</p><p>Hands-on labs show how to jump between dashboard widgets, explorations, and Cognos mobile.</p>',
                'body_ar' => '<h2>تحليلات معززة موثوقة</h2><p>نستكشف مساعد الذكاء الاصطناعي ونقارن جودة التوقعات ونوضح كيفية توثيق منطق الأعمال ليثق أصحاب المصلحة في الرؤى الآلية.</p><p>تُظهر التمارين العملية كيفية التنقل بين عناصر اللوحة والاستكشافات وتطبيق Cognos للهواتف.</p>',
                'cta_note_en' => 'Bring enterprise BI discipline into every project with our mentoring.',
                'cta_note_ar' => 'طبّق انضباط ذكاء الأعمال المؤسسي في كل مشروع بمرافقتنا التدريبية.',
                'hero_image' => 'https://via.placeholder.com/800x400/0F62FE/ffffff?text=Cognos+AI',
                'status' => 'published',
                'display_order' => 1,
            ],
            [
                'slug' => 'enterprise-reporting',
                'title_en' => 'Enterprise Reporting Workflows',
                'title_ar' => 'مسارات إعداد التقارير المؤسسية',
                'summary_en' => 'Automate bursting, schedule PDF delivery, and manage multilingual report templates.',
                'summary_ar' => 'أتمت توزيع التقارير، وجدول إرسال ملفات PDF، وأدر قوالب التقارير متعددة اللغات.',
                'body_en' => '<h2>Enterprise-Grade Distribution</h2><p>We configure bursting rules, SMTP settings, and audit trails so leadership always receives the latest numbers.</p><p>You will also learn how to structure data modules that feed both dashboards and paginated reports.</p>',
                'body_ar' => '<h2>توزيع بمستوى الشركات</h2><p>نضبط قواعد التوزيع التلقائي وإعادات البريد وسجلات التدقيق لضمان وصول أحدث الأرقام للإدارة.</p><p>ستتعلم كذلك كيفية بناء نماذج البيانات التي تغذي اللوحات والتقارير الصفية في آن واحد.</p>',
                'cta_note_en' => 'Bring enterprise BI discipline into every project with our mentoring.',
                'cta_note_ar' => 'طبّق انضباط ذكاء الأعمال المؤسسي في كل مشروع بمرافقتنا التدريبية.',
                'hero_image' => 'https://via.placeholder.com/800x400/0043CE/ffffff?text=Cognos+Reports',
                'status' => 'published',
                'display_order' => 2,
            ],
        ],
    ];

    return [
        'topics' => $topics,
        'content' => $content,
    ];
}